#!/usr/bin/env python3
"""Streaming console filter for the supervised live server.

WHY: ``run_live_server.sh`` mirrors the whole server log to the terminal, which
makes the terminal useless as a status display. A single 2026-07-30 session put
535 identical ``dealer poll failed`` warnings, 535 ``httpx`` request lines, 66
scheduler re-arm lines, a 939-symbol websocket subscription dump and a
5-minute memory-keeper tick on screen — and buried in the middle of it, the one
line that actually mattered (an expired Schwab token) scrolled past unnoticed.

This filter changes only what the *terminal* shows. ``logs/live_server/
server_YYYYMMDD.log`` still receives every byte, unfiltered — this reads the
mirror, never the sink, so nothing here can lose data.

Two mechanisms:

1. **Drop list** — known-noisy INFO chatter with no operational meaning.
2. **Repeat collapse** — any log record repeated within ``--window`` seconds is
   counted rather than printed, and the count is reported when the pattern next
   surfaces. This is what turns 535 identical warnings into roughly one line
   every five minutes, *without* hiding the first occurrence.

Anything not recognised is passed through unchanged: the failure mode is
"too much output", never "silently swallowed".

Usage:
    tail -F server.log | scripts/live_console_filter.py
    VERBOSE=1 ...            # disable all filtering (pass-through)
"""

from __future__ import annotations

import argparse
import os
import re
import sys
import time

#: Log records look like ``2026-07-30 11:22:58,582 INFO [logger.name] message``.
LOG_RECORD = re.compile(
    r"^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d+ (?P<level>[A-Z]+) \[(?P<logger>[^\]]+)\] (?P<msg>.*)$",
    re.DOTALL,
)

#: Lines dropped outright. Each entry is (regex, reason-for-the-drop).
DROP_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"INFO \[httpx\] HTTP Request:"), "per-request HTTP chatter"),
    (re.compile(r"INFO \[alpaca\.data\.live\.websocket\]"), "websocket lifecycle + 939-symbol subscribe dump"),
    (re.compile(r"INFO \[UI\.nightly_scheduler\] Nightly scheduler(:| armed)"), "scheduler arm/fire/complete ticks"),
    (re.compile(r"INFO \[__main__\] Memory keeper: RSS="), "5-minute memory keeper tick"),
    (re.compile(r"Swing stream heartbeat:"), "2-minute stream heartbeat"),
    (re.compile(r"^\d+\.\d+\.\d+\.\d+ - - \[.*\] \".*\" \d+ -$"), "werkzeug HTTP access log"),
    (re.compile(r"live feature panel: \d+/\d+ tickers built"), "feature panel progress"),
    (re.compile(r"features built for [A-Z.]+$"), "feature matrix progress"),
    (re.compile(r"INFO \[schwab\.auth\] Loading token from file"), "token load notice"),
    (re.compile(r"\[spy_intraday_trader\] .* aligned coverage="), "context alignment detail"),
]

#: The xgboost/sklearn artifact-version warning is a fixed multi-line block. It
#: is real but unchanging, so it is collapsed to one line the first time.
MODEL_WARNING_PATTERNS = [
    re.compile(r"WARNING: /__w/xgboost/.*error_msg\.h"),
    re.compile(r"configuration generated by an older version of XGBoost"),
    re.compile(r"`Booster\.save_model` from that version first"),
    re.compile(r"https://xgboost\.readthedocs\.io"),
    re.compile(r"for more details about differences between saving model"),
    re.compile(r"InconsistentVersionWarning: Trying to unpickle"),
    re.compile(r"^\s*warnings\.warn\(?\s*$"),
    re.compile(r"https://scikit-learn\.org/stable/model_persistence"),
]

MODEL_WARNING_NOTICE = (
    "[console] model artifact version warnings (xgboost/sklearn) suppressed — see log"
)

#: Digits, hex ids and quoted payloads vary between otherwise-identical records;
#: normalise them so repeats collapse onto one signature.
_NUMBERS = re.compile(r"\d+")
_TICKER_TAG = re.compile(r"^\[[A-Z.]{1,6}\] ")


def signature(level: str, logger_name: str, msg: str) -> str:
    """Collapse a record to what makes it 'the same message' for repeat counting."""
    body = _TICKER_TAG.sub("", msg)  # [SPY] / [QQQ] variants are one message
    body = _NUMBERS.sub("#", body)
    return f"{level}|{logger_name}|{body[:160]}"


class ConsoleFilter:
    def __init__(self, window: float = 300.0, clock=time.monotonic) -> None:
        self.window = window
        self.clock = clock
        self._last_emit: dict[str, float] = {}
        self._suppressed: dict[str, int] = {}
        self._model_warning_seen = False

    def __call__(self, line: str) -> str | None:
        """Return the text to print, or ``None`` to suppress this line."""
        stripped = line.rstrip("\n")

        for pattern in MODEL_WARNING_PATTERNS:
            if pattern.search(stripped):
                if self._model_warning_seen:
                    return None
                self._model_warning_seen = True
                return MODEL_WARNING_NOTICE

        for pattern, _reason in DROP_PATTERNS:
            if pattern.search(stripped):
                return None

        match = LOG_RECORD.match(stripped)
        if match is None:
            # Banner text, subprocess stdout, blank lines: always pass through.
            return stripped

        key = signature(match["level"], match["logger"], match["msg"])
        now = self.clock()
        last = self._last_emit.get(key)
        if last is not None and (now - last) < self.window:
            self._suppressed[key] = self._suppressed.get(key, 0) + 1
            return None

        self._last_emit[key] = now
        held = self._suppressed.pop(key, 0)
        if held:
            mins = int(self.window // 60)
            return f"{stripped}   [+{held} identical suppressed in the last ~{mins}m]"
        return stripped


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--window",
        type=float,
        default=float(os.environ.get("CONSOLE_REPEAT_WINDOW", "300")),
        help="seconds before an identical record is shown again (default 300)",
    )
    args = parser.parse_args()

    passthrough = os.environ.get("VERBOSE", "0") == "1"
    console = ConsoleFilter(window=args.window)

    for line in sys.stdin:
        try:
            out = line.rstrip("\n") if passthrough else console(line)
        except Exception:  # noqa: BLE001 - a filter bug must never eat the console
            out = line.rstrip("\n")
        if out is not None:
            print(out, flush=True)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (BrokenPipeError, KeyboardInterrupt):
        raise SystemExit(0)
